### PR TITLE
not needed anymore and causes more trouble that it solves

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
xref: https://github.com/galaxyproject/tools-iuc/issues/1833

**Comment by moskalenko** [comment]
Unfortunately, it's not that simple:

[galaxy@galaxy3 galaxy]$ conda install dunovo
Fetching package metadata .................
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - dunovo -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

**Comment by nsoranzo** [comment]
@moskalenko The correct command is:
```
conda create -n __dunovo@2.0.12 dunovo==2.0.12
```
which works fine for me.

**Comment by moskalenko** [comment]
Thank you both for information.

**Comment by NickSto** [comment]
Implemented in 1de35de

**Pull request closed without merging**
